CREATE TYPE "UserStatus" AS ENUM ('ACTIVE', 'LOCKED', 'SUSPENDED');
CREATE TYPE "MatchMode" AS ENUM ('TRAINING', 'RANKED');
CREATE TYPE "MatchStatus" AS ENUM ('WAITING', 'LOADING', 'ACTIVE', 'FINISHED', 'CANCELLED');
CREATE TYPE "MatchResult" AS ENUM ('WIN', 'LOSS', 'DRAW');
CREATE TABLE "User" ("id" TEXT PRIMARY KEY, "username" VARCHAR(24) NOT NULL, "email" VARCHAR(254) NOT NULL, "passwordHash" TEXT NOT NULL, "emailVerifiedAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, "lastLoginAt" TIMESTAMP(3), "status" "UserStatus" NOT NULL DEFAULT 'ACTIVE', "failedLoginAttempts" INTEGER NOT NULL DEFAULT 0, "lockedUntil" TIMESTAMP(3));
CREATE UNIQUE INDEX "User_username_key" ON "User"("username");
CREATE UNIQUE INDEX "User_email_key" ON "User"("email");
CREATE TABLE "VerificationToken" ("id" TEXT PRIMARY KEY, "userId" TEXT NOT NULL REFERENCES "User"("id") ON DELETE CASCADE, "tokenHash" TEXT NOT NULL, "expiresAt" TIMESTAMP(3) NOT NULL, "usedAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE UNIQUE INDEX "VerificationToken_tokenHash_key" ON "VerificationToken"("tokenHash");
CREATE INDEX "VerificationToken_userId_expiresAt_idx" ON "VerificationToken"("userId","expiresAt");
CREATE TABLE "RecoveryToken" ("id" TEXT PRIMARY KEY, "userId" TEXT NOT NULL REFERENCES "User"("id") ON DELETE CASCADE, "tokenHash" TEXT NOT NULL, "expiresAt" TIMESTAMP(3) NOT NULL, "usedAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE UNIQUE INDEX "RecoveryToken_tokenHash_key" ON "RecoveryToken"("tokenHash");
CREATE INDEX "RecoveryToken_userId_expiresAt_idx" ON "RecoveryToken"("userId","expiresAt");
CREATE TABLE "Session" ("id" TEXT PRIMARY KEY, "userId" TEXT NOT NULL REFERENCES "User"("id") ON DELETE CASCADE, "refreshTokenHash" TEXT NOT NULL, "userAgent" VARCHAR(300), "ipHash" TEXT, "expiresAt" TIMESTAMP(3) NOT NULL, "revokedAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE UNIQUE INDEX "Session_refreshTokenHash_key" ON "Session"("refreshTokenHash");
CREATE INDEX "Session_userId_expiresAt_idx" ON "Session"("userId","expiresAt");
CREATE TABLE "PlayerProfile" ("userId" TEXT PRIMARY KEY REFERENCES "User"("id") ON DELETE CASCADE, "level" INTEGER NOT NULL DEFAULT 1, "experience" INTEGER NOT NULL DEFAULT 0, "totalAura" INTEGER NOT NULL DEFAULT 0, "currentRank" TEXT NOT NULL DEFAULT 'SEM_PRESENCA', "mmr" INTEGER NOT NULL DEFAULT 1000, "wins" INTEGER NOT NULL DEFAULT 0, "losses" INTEGER NOT NULL DEFAULT 0, "winStreak" INTEGER NOT NULL DEFAULT 0, "tutorialCompleted" BOOLEAN NOT NULL DEFAULT false, "selectedCosmetics" JSONB NOT NULL DEFAULT '{}', "audioSettings" JSONB NOT NULL DEFAULT '{"master":0.8,"music":0.6,"effects":0.8,"muted":false}', "graphicsSettings" JSONB NOT NULL DEFAULT '{"quality":"AUTO","reducedMotion":false,"cameraShake":true}');
CREATE INDEX "PlayerProfile_mmr_idx" ON "PlayerProfile"("mmr" DESC);
CREATE TABLE "Match" ("id" TEXT PRIMARY KEY, "mode" "MatchMode" NOT NULL, "status" "MatchStatus" NOT NULL, "seed" INTEGER NOT NULL, "startedAt" TIMESTAMP(3), "endedAt" TIMESTAMP(3), "winnerId" TEXT REFERENCES "User"("id"), "finishReason" TEXT, "serverVersion" TEXT NOT NULL DEFAULT '1.0.0');
CREATE INDEX "Match_status_startedAt_idx" ON "Match"("status","startedAt");
CREATE TABLE "MatchParticipant" ("matchId" TEXT NOT NULL REFERENCES "Match"("id") ON DELETE CASCADE, "userId" TEXT NOT NULL REFERENCES "User"("id"), "score" INTEGER NOT NULL DEFAULT 0, "aura" INTEGER NOT NULL DEFAULT 0, "remainingEgo" INTEGER NOT NULL DEFAULT 100, "highestCombo" INTEGER NOT NULL DEFAULT 0, "accuracy" DOUBLE PRECISION NOT NULL DEFAULT 0, "perfectActions" INTEGER NOT NULL DEFAULT 0, "mistakes" INTEGER NOT NULL DEFAULT 0, "spamViolations" INTEGER NOT NULL DEFAULT 0, "mmrBefore" INTEGER NOT NULL, "mmrAfter" INTEGER, "disconnectedAt" TIMESTAMP(3), "result" "MatchResult", PRIMARY KEY ("matchId","userId"));
CREATE INDEX "MatchParticipant_userId_matchId_idx" ON "MatchParticipant"("userId","matchId");
CREATE TABLE "MatchEvent" ("id" BIGSERIAL PRIMARY KEY, "matchId" TEXT NOT NULL REFERENCES "Match"("id") ON DELETE CASCADE, "type" TEXT NOT NULL, "sequence" INTEGER NOT NULL, "payload" JSONB NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX "MatchEvent_matchId_sequence_idx" ON "MatchEvent"("matchId","sequence");
